version: '3'
services:
    fastapi:
        build:
            context: .
        ports:
            -   "80:80"
        depends_on:
            -   redis
        links:
            -   redis
    redis:
        image: redis
        ports:
            -   "6379:6379"